after_script:
- make odoo-stop
before_script:
- make odoo-start
env:
- TOXENV=py27
- TOXENV=flake8
- TOXENV=readme
install:
- make develop
language: python
script:
- make test
services:
- docker
sudo: required
